packages:
  - 'packages/**'
  - '!packages/taro-cli/templates/**'
  - '!**/__tests__/**'
  - 'npm/**'
  - 'crates/native_binding'
  - 'examples/mini-program-example'
  - 'examples/demo-vue2'
  - 'examples/demo-vue3'
